buildpack:
  name: Blazar-Buildpack-Java-prebuilt

buildResources:
  memoryMb: 4096

env:
  PROJECT_NAME: "mbknor-jackson-jsonschema"
  PUBLISH_DIR_WITHOUT_VERSION: "${PROJECT_NAME}_2.13"
  SBT_TAR_VERSION: "1.12.3"
  SBT_TAR_FILE_NAME: "sbt-$SBT_TAR_VERSION.tgz"
  SBT_TAR_LINK: "https://github.com/sbt/sbt/releases/download/v$SBT_TAR_VERSION/$SBT_TAR_FILE_NAME"
  SBT_FILE: "/tmp/sbt-install/$SBT_TAR_FILE_NAME"
  HOME_BIN: "$HOME/bin"
  SBT_BIN: "${HOME_BIN}/sbt/bin"
  PROJECT_VERSION: ""
  PUBLISH_DIR: ""

stepActivation:
  uploadAndNotify:
    branches: ['hubspot']

before:
  - description: "Download and install sbt"
    commands:
      - mkdir -p /tmp/sbt-install
      - mkdir -p $HOME_BIN
      - wget --quiet $SBT_TAR_LINK -O $SBT_FILE
      - tar -xvzf $SBT_FILE -C $HOME_BIN
      - chmod u+x $SBT_BIN/sbt
      - rm -rf /tmp/sbt-install

  - description: "Test across all supported Scala Versions"
    commands:
      - $SBT_BIN/sbt +test

  - description: "Package + Publish Local"
    commands:
      - $SBT_BIN/sbt +publish

  - description: "Move artifacts to upload directory"
    commands:
      - |
        project_version="$($SBT_BIN/sbt -warn --batch --no-colors 'print version')"
        for i in $(find target -name "scala-2.1*")
        do
            scala_dir="$(basename $i)"
            scala_version="${scala_dir#scala-}"
            artifact_dir="mbknor-jackson-jsonschema_$scala_version-$project_version"
            mkdir $artifact_dir
            find $i -maxdepth 1 -name "*-$project_version-javadoc.jar" -exec cp {} "$artifact_dir/javadoc.jar" \;
            find $i -maxdepth 1 -name "*-$project_version-sources.jar" -exec cp {} "$artifact_dir/sources.jar" \;
            find $i -maxdepth 1 -name "*-$project_version.jar" -exec cp {} "$artifact_dir/main.jar" \;
            find $i -maxdepth 1 -name "*-$project_version.pom" -exec cp {} "$artifact_dir/pom.xml" \;
        done

  - name: uploadAndNotify
    description: "Notifying deploy service"
    activeByDefault: false
    commands:
      - command: publish-build-success --project
